### ISSUE TITLE
Applet/algorithm categories cannot be removed in Project Settings portal

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#1010]
**Category**
Bug

**Problem**
Categories can only be added in the `Applet` and `Algorithm` pages of the `Project Settings Portal`. These can only be removed via the admin portal or REST interface.

**Request**
There should be a `-` button next to each category entry that allows project administrators to remove that category.

**Comment by ermbutler** [comment]
@marktaipan-cvisionai Not sure if the current bug is keeping this from working, but you should be able to empty the field to remove the category.

This is not as intuitive as a minus button, but on the branch for PR #1040 I just tested and clearing the field to "" does remove a category if you need to do it ahead of getting the - button.
