### ISSUE TITLE
Project settings/applet categories are duplicated on refresh

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#1011]
**Category**
Bug

**Problem**
In the `Project Settings` -> `Applet` page, every time an applet page is refreshed the categories are duplicated. This becomes problematic when the applet is updated because the categories are duplicated themselves. It is also problematic because if an admin updates the applet several times, the page will quickly become overly vertically expanded and difficult to use.

**Request**
The categories in this page should not be duplicated on refresh.

**Comment by ermbutler** [comment]
This is fixed in PR #1040 
https://github.com/cvisionai/tator/pull/1040/commits/b65b94c89b81549abb5ad22e1bf3ea4f1f267f53
