### ISSUE TITLE
Support web login via token

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#102]
Enable bypassing the login view if a token is supplied and the user can be authenticated that way. Presumably the token could be supplied via either a URL parameter or request body if the page supports a POST. 

It's possible this would be implemented via the REST side, so that a POST can be used or if deemed secure can be added to the existing login page via a URL query parameter. Upon successful login, the service should respond with a 301 to redirect to the desired page on the site.

**Comment by bctcvai** [comment]
One should look at jwt-gateway for the syntax to login the user after token authentication is complete.

**Comment by bctcvai** [comment]
@henxing - is this closed based on your SAML work?

**Comment by henxing** [comment]
It's not specifically via token, but it does check all the boxes.

**Comment by jrtcppv** [comment]
Closed by #1208.
