### ISSUE TITLE
Saved searches missing from filter UI dropdown

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#1054]

**Comment by 2022H1030042G** [comment]
Hi, I would like to work on this issue, is it available?

**Comment by bctcvai** [comment]
Yes. Thank you for any contributions. I wrote issue somewhat tersely for internal consumption if you need more details let me know. 

The general idea is the filter UI in project detail let's you filter on a section, but for some reason in the dropdown it is only listing sections with a static UUID instead of sections built from lucene queries. I referred to the latter "Saved searches" as that is what the UI calls them but no such term exists in the backend code.

**Comment by bctcvai** [comment]
I know contributing to an open source project can be a challenge, especially for the first time. Just to give you a 5-cent tour here to get started:

[/ui/src/js/components/filter-data.js](https://github.com/cvisionai/tator/blob/main/ui/src/js/components/filter-data.js) - Contains the logic for populating the drop-down.
[/ui/src/js/components/filter-data.js](https://github.com/cvisionai/tator/blob/main/ui/src/js/components/filter-condition.js) - Contains the logic for displaying the right drop down when the user selects something like '_section' in the filter UI. 

Thanks again for taking an interest in the project!
