### ISSUE TITLE
Time-based buffer for playback

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#110]
Split out scrub / play buffer so that 1080p or 4k playback doesn't download the entire video for playback usage.

**Comment by bctcvai** [comment]
All buttons are unmasked at all times, so madly clicking things can cause problems. (or just being really fast)

Either the player needs to interlock buttons to prevent things from happening in bad states
Or gracefully cancel pending seeks if a play is started

**Comment by bctcvai** [comment]
Eventually, when we add temporal compression a general purpose setup might be:

Scrub at 360p 1FPS
Play at 720p full FPS
Pause at 1080p

**Comment by marktaipan-cvisionai** [comment]
Closed by e196ae8d8bac1fbe8c5421b0b1821e0709121dc6
