### ISSUE TITLE
Switch File endpoint to use object based storage

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#1142]
**Category**
Bug

**Problem**
File endpoint is still using NFS and not object based storage

**Request**
Fix bug. One line that needs to be changed is the following (from `FileField` to `CharField` that mimics other `Resource` based paths)
`path = FileField(upload_to=ProjectBasedFileLocation, null=True, blank=True)`

**Comment by bctcvai** [comment]
Dupe of #1125.
