### ISSUE TITLE
Add tooltips to video controls buttons

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#1156]
**Category**
Feature Request

**Problem**
Currently there are no tooltips for the newer buttons in the annotator's video control UI. This reduces accessibility.

**Request**
Add tooltips where they are missing in `annotation-player` and `annotation-multi`

**Comment by ermbutler** [comment]
Note: Using the attribute "tooltip" you can add the currently styled tooltip which works great -- what you'll see and may need to address in this is that the color charcoal it uses sometimes doesn't work on the item you add the tooltip too (it blends in) --- maybe a class to alter it in those scenarios would work, or we pick a brighter color (like white background or light blue?) so it always stands out and is consistently styled. I added a class to alter the current tooltip direction for some cases, ie. "tooltip-left" which whoever picks this up can search and use as example.
