### ISSUE TITLE
Improvements to the algorithm launch modal

### ISSUE THREAD

**Issue by henxing** [cvisionai/tator#1173]
It is easy to run an algorithm on every image/video in a project by launching from the main project detail page. It would be helpful if the number of images and hours of video selected as input was on the confirmation popup for launching an algorithm to avoid running on more media than intended.

**Comment by marktaipan-cvisionai** [comment]
Doesn't include hours, but the number of media is displayed upon launching a workflow in the `project-detail` view.
Closed with de57b98
