### ISSUE TITLE
Fix issue regarding mobile photos orientation in Tator

### ISSUE THREAD

**Issue by ermbutler** [cvisionai/tator#1179]
There seems to be differences in Chrome and Edge with regards to how phone photos present in the annotator.

They should reflect the same thing as the backend, and if there is a difference that it can be fixed (ie. choose the rotation) from the tool.

**Comment by bctcvai** [comment]
- Canvas dimensions need to be calculated correctly as well, right now, similarly those dimensions are fetched from PIL on image import.
- Lastly, the underlying image texture needs to be loaded consistently prior to shipping to the canvas; basically 0,0 needs to be the upper left hand corner of the image as one wants it displayed; and 1280,720 is the lower right.

**Comment by ermbutler** [comment]
I was able to handle this on the front end by reading the data in browser before saving.
