### ISSUE TITLE
SAM Integration

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#1214]
Add an intuitive method to initiate creation of a box or poly with Segment Anything, recently released from Meta. Building this integration into the core application will allow us to use canvas data directly rather than relying on an image retrieved from the `GetImage` endpoint. The demo application from Meta is a good reference for how to implement the UI.

**Comment by bctcvai** [comment]
Relevant URL:

https://github.com/facebookresearch/segment-anything/tree/main/demo

- Underlying ONNX runner looks cool, multi threaded WASM. Requires secure context which we need for video decoder anyway.

Probably worth another issue but checking out yolov5 performance here might be interesting against what we have from tensorflow.js 
https://cloudblogs.microsoft.com/opensource/2021/09/02/onnx-runtime-web-running-your-machine-learning-model-in-browser/

**Comment by bctcvai** [comment]
Might be neat to also look at this at some point, for both the embeddings requirement as well as just general in-browser inference capabilities:

https://github.com/webonnx/wonnx

**Comment by bctcvai** [comment]
Have model server configuration in a poly type definition

**Comment by marktaipan-cvisionai** [comment]
Closed, canvas applet framework supports SAM integration
