### ISSUE TITLE
Fix caching logic for presigned

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#1250]
Does not account for duration length in presigned cache scheme.

**Comment by jrtcppv** [comment]
Recommend resolving this with a query param that forces a presigned url refresh, otherwise we will never use the cache.

**Comment by bctcvai** [comment]
Given the presigned cache was a workaround to directly serving presigned URLs and most deployments have moved to proxy approaches, it might be valid just to nix the complexity of presigned urls and this cache approach entirely. The Redis lookup makes implementing any kind of key introspection quite obtuse.
