### ISSUE TITLE
Media Gallery Filter on ID fails: `400 bad request` then `t.entries is not a function`

### ISSUE THREAD

**Issue by sbatchelder** [cvisionai/tator#1259]
Media Gallery Filter on ID fails. Returns two `400 bad request` responses and one `TypeError: t.entries is not a function or its return value is not iterable`

Haven't found this to happen on other filter types for Media yet. 
 

![image](https://github.com/cvisionai/tator/assets/44208509/bc46c2bc-a734-49b7-884f-f34774b0e61b)

**Comment by marktaipan-cvisionai** [comment]
Closed with v1.0.0 hotfix
