### ISSUE TITLE
REST Interface UI fails (ssl/cors docker/proxy related)

### ISSUE THREAD

**Issue by sbatchelder** [cvisionai/tator#1269]
When using the REST Interface UI on a server using SSL, queries fail with `URL scheme must be "http" or "https" for CORS request.`
If I copy-past the query into the url bar directly, the request is properly proxy-ed.  

The deployment is from the main branch [28b242b](https://github.com/cvisionai/tator/commit/28b242b2bcd9347bc1d3457f85191cdd7178714d), uses docker-compose, and SSL is being proxied by apache2

![image](https://github.com/cvisionai/tator/assets/44208509/a6a4833c-a21d-4aa0-8f91-cb061e793626)

vs.

![image](https://github.com/cvisionai/tator/assets/44208509/cc9f7207-d4e1-4f8f-84ac-25f4db5f7522)

SSL config

```
  <VirtualHost *:80>
    ServerName potator.whoi.edu
    Redirect "/" "https://potator.whoi.edu/"
  </VirtualHost>

  <VirtualHost _default_:443>
    ServerName potator.whoi.edu

    SSLEngine on
    SSLCertificateFile	/etc/ssl/certs/<file>.pem
    SSLCertificateKeyFile /etc/ssl/private/<file>.key

    ProxyPreserveHost On
    ProxyRequests Off
    ProxyVia On
    ProxyPass / http://0.0.0.0:8080/ connectiontimeout=600 timeout=600 Keepalive=On
    ProxyPassReverse / http://0.0.0.0:8080/
  </VirtualHost>
  ```

**Comment by jrtcppv** [comment]
@sbatchelder In the .env file did you also change the `MAIN_HOST` parameter to potator.whoi.edu?

I think the solution might be to introduce a proxy domain parameter that would be used exclusively in the REST schema.

**Comment by jrtcppv** [comment]
After some analysis, we think the problem might be resolved if you set the variable `REQUIRE_HTTPS=TRUE` in your `.env` file, especially if you were able to set `MAIN_HOST` to potator.whoi.edu already.

**Comment by sbatchelder** [comment]
This fixed it! Thanks!
