### ISSUE TITLE
Allow media to be filtered by an annotation query

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#127]
It is currently possible to filter annotations by a media query using the `media_query` rest parameter. The opposite should also be possible by adding a `annotation_query` rest parameter to the `Media` endpoint.

**Comment by bctcvai** [comment]
This should be pretty doable, because once you have a rowset of all the annotations they are in a flat table, and you can turn that into a subquery for Media. 

Something like:
```
Media.objects.filter(pk__in=Subquery(localization_queryset.values('media')))
```

(This implies the localization list is a query set from IDs presumably from ES)

**Comment by jrtcppv** [comment]
OBE'd by #267.
