### ISSUE TITLE
Add additional styles to attributes

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#1298]
**Category**
Feature Request

**Problem**
It would be nice to add specific styling using the `style` field for each attribute type. For instance this could force specific colors, font strength, and label/value column split. These would override the defaults. It would help make the UI a little more readable especially with tiered attributes and lengthy names.

**Request**
Modify `attribute-panel.js` to allow the add and removing of specific CSS classes to accommodate:
- Changing the font style of the attribute label
- Changing the font color of the attribute label
- Changing the column width of the attribute label and text field

**Comment by bctcvai** [comment]
I like this idea; added a `group` key whilst you are in there might be nice. That could lay the foundation for attribute groups a la: https://github.com/cvisionai/tator/issues/1202

**Comment by marktaipan-cvisionai** [comment]
Closed with d988fbd
Will make a new issue to incorporate the `group` key
