### ISSUE TITLE
No support for HEIC (HEIF) image type in media upload

### ISSUE THREAD

**Issue by ermbutler** [cvisionai/tator#1326]
Browsers don't currently recognize the image/HEIC type and the file type isn't showing when a file input accepts="images/*" Users can manually convert right now and upload in another larger format.

For tator to accept HEIC we would need to accept="images/*,.heic" on the input, and then convert it on client side(https://www.npmjs.com/package/heic2any), or on ingestion (which would be the longer term solution -- examples from @henxing https://github.com/carsales/pyheif and https://github.com/bigcat88/pillow_heif)

**Comment by bctcvai** [comment]
That pillow one would drop in pretty easily from taking a closer look.
