### ISSUE TITLE
Multiple memberships create does not work

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#1374]
Also revisiting the membership create view persists the user selections, this should be cleared when the view is loaded. To test this, try creating a membership for 5-10 users at once, some will be created some will not. @BGWoodward has reported that invitations and versions also do not work when multiple are involved.

**Comment by bctcvai** [comment]
I think the code fails out on first error. In the multi-user case I ran into that once, and it invited 3/5 users because the 4th one had an error. I am not sure about the version comment.

**Comment by jrtcppv** [comment]
Wondering if this should just be a backend fix, allow POST of multiple memberships, versions, invitations in one request. That way it could be an atomic operation (create all or none).

**Comment by bctcvai** [comment]
Perhaps; I could also see it returning a list of the ones that were successful or not vs. "all or nothing". The issue I could see with all or nothing is if some unknown error happens after sending 2 out of 5 out or something. That's effectively what is happening now.

**Comment by ermbutler** [comment]
Typically for a list, the backend all or nothing is preferred by the front end. I am taking a look at the function, and moving where I am looping the invitations https://github.com/cvisionai/tator/issues/1266 but the backend approach will be easier to deal with / less chance for front-end interruption, etc.
