### ISSUE TITLE
Adjust text overlay position

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#1378]
**Category**
Bugfix

**Problem**
Time text overlay on video canvas is not centered. The left border of the text is halfway instead of the center of the text being halfway in the canvas width.

**Request**
Adjust overlay so that the text is always centered. Could also be moved to the left side of the video and in a smaller text (e.g. top left). This would be similar to the x,y mouse hover text overlay.

**Comment by marktaipan-cvisionai** [comment]
As part of this, the style should also be applied from the overlayConfig field in the media type. Currently the time overlay is hardcoded to use `this.overlayTextStyle`

**Comment by bctcvai** [comment]
Resolved in #1465
