### ISSUE TITLE
Recently saved localization not auto-selected in entity browser

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#1383]
**Category**
Bugfix

**Problem**
When a localization is saved, sometimes it is not selected in the entity browser. Instead the previously selected localization is selected.

**Request**
The most recent localization should always be saved.

**Notes**
Worth looking at if the hiding of the annotation browser is stopping the update/selection of the entity browser. This bug appears to have appeared after 1.1, which includes the new feature of annotation browser not being automatically opened when saved.

**Comment by bctcvai** [comment]
Do you want this on 1.2.0?

**Comment by marktaipan-cvisionai** [comment]
Yes please

**Comment by marktaipan-cvisionai** [comment]
Closed with [084e138](https://github.com/cvisionai/tator/commit/084e138570780e1b8574f77b351cca3684441f08)
