### ISSUE TITLE
Video frame thumbnail not shown in localization gallery panel

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#1393]
**Category**
Bugfix

**Problem**
Frame thumbnail is not shown in localization gallery's entity panel. Specifically localizations from video frames. Localizations from images appear to work.

**Request**
Fix bug. Frame thumbnail should be visible with drawn localization in the localization gallery's entity panel

**Comment by marktaipan-cvisionai** [comment]
OBE

**Comment by danellecline** [comment]
@marktaipan-cvisionai   We could sure use this feature in an MBARI workflow that uses standalone tator. I'm happy to make a contribution to the code base by adding this feature.  I see this is slated for the 1.3.0 milestone. Any idea how far off from 1.3.0 milestone is?  We are using 1.2.5.

**Comment by marktaipan-cvisionai** [comment]
@danellecline This has been fixed on `main` and is slated for 1.3.0. We're currently looking to freeze the 1.3.0 release in a couple of weeks. Hope that helps!

**Comment by danellecline** [comment]
Many thanks, @marktaipan-cvisionai. That is great news! Thank you for the fast response. We appreciate that, and we appreciate that Tator is open source. I hope that we can contribute to it in the future.

**Comment by marktaipan-cvisionai** [comment]
Absolutely welcome the support, thanks! Let us know if there are specific issues that you folks would be interesting in taking on and we can provide guidance.

**Comment by danellecline** [comment]
Thanks! @marktaipan-cvisionai . Our robotics group at MBARI is interested in multiview for images. That exists for video, but not images, right? If so, I can tackle that if you give me a rough sketch of the work.  I'm off work until April 22 and can revisit it if you think that's a good feature to add.

**Comment by marktaipan-cvisionai** [comment]
Yes, you're correct. There is only a multi-view video annotator right now. That would be a good feature to add; albeit it'll involve a decent amount of work. Let us know when you're ready to take a look at it. We can create a GitHub issue with an outline of work/test acceptance criteria then.

**Comment by danellecline** [comment]
ok. Will do.
