### ISSUE TITLE
Change camel case rest parameters to snake case

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#141]
Camel case parameters: minLevel, frameRanges, forceScale, sendAsFile, excludeParents, colorMap;

**Comment by jrtcppv** [comment]
We could also change everything to camel case, this should just have a consistent convention.

**Comment by bctcvai** [comment]
I'd opt for all snake case if we wanted consistency given its far less churn. A new one... someone.. just added was `elementalId`.

**Comment by bctcvai** [comment]
We also use snakecase more in the code. I think at one point we had read some REST guidance that query args were "supposed to be" camel, but I think consistency is better than purity.
