### ISSUE TITLE
Make localization graphic endpoint

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#148]
Utilizing media_util in REST, make a localization graphic so that localization thumbnails can be captured in a similar conops to StateGraphic. E.g. /rest/LocalizationGraphic/<id>

Ideally this api can be flexible to do the following via arguments:
- Persist the thumbnail via a temporary file for N hours

**Comment by marktaipan-cvisionai** [comment]
Closed by: https://github.com/cvisionai/tator/commit/48b6e71ca38e5f8a022e56e6fef120dc1d8c816d

Note: There's a lot of room for additional work for this endpoint. For now, the endpoint can only accept GET requests and can only create a new thumbnail based on the provided parameters.
