### ISSUE TITLE
REST version and localization DELETE fails

### ISSUE THREAD

**Issue by sbatchelder** [cvisionai/tator#1486]
I find myself unable to delete Versions or bulk delete Localizations by version using the REST interface.

If there isn't a quick fix available, I'm going to remove versions and localizations using the django shell.
What are best practices for deleting versions and localizations using the django orm? Thank you

Also the UI gives conflicting warnings:

## trying to delete version with UI

![image](https://github.com/cvisionai/tator/assets/44208509/2e6fee9c-99b4-40be-937c-232763de38ce)

![image](https://github.com/cvisionai/tator/assets/44208509/efb68a03-67bc-4689-991c-2ad15d9425c1)

#### Attempting to delete version directly gives the same error as above, as expected

`DELETE` `https://tator.whoi.edu/rest/Version/16`
```
# Response
Code 400 - "Cannot delete version with annotations! Found 6491 localizations, 0 states!"
```

#### Attempting to delete all localizations associated with a version "fails successfully"

`DELETE` `https://tator.whoi.edu/rest/Localizations/1?type=1&version=16&merge=1&show_deleted=0`
```
# Response
Code 200 -  "message": "Successfully deleted 0 localizations!" 
```

tator version:  `main` branch circa today, commit [c2b400d](https://github.com/cvisionai/tator/commit/c2b400d1027ced5231d32e585790629d3f5d2547)

**Comment by bctcvai** [comment]
Sidney: 

I suspect its a corner case / gap in the unit tests with regard to deleting whole versions. I'll tag this issue in a PR to rectify the behavior + fill in the test gap.

A workaround is possible on the commit referenced. As a heads up, you'll notice `DELETE` via HTTP leaves the database record in place. This had always been the case for `Media` but recently added for Metadata in preparation for a larger PR. There is a new column on the record `variant_deleted` set to True to inform the various `GET`/`PATCH` to treat that record as though its not there (`show_deleted=0`) 

The workaround is to modify the `DELETE` call slightly:

```
DELETE https://tator.whoi.edu/rest/Localizations/1?type=1&version=16&merge=0&show_deleted=1
required body: {'prune': 1}

# Currently we pass the 'prune' argument to explicitly mean to actually delete the row from the database.
# This is in the body of the delete, which is problematic if using the tator-py bindings. A future PR will move this to a query argument to make it more accessible as a lot of clients don't send HTTP request bodies on DELETE.

```

Alternatively, your intuition to use django-shell to manually delete the records in question will also work.
```python
from main.models import Localization
set=Localization.objects.filter(project=1,type=1,version=16)
set._raw_delete(set.db)
```

**Comment by bctcvai** [comment]
This PR should resolve this issue: 
https://github.com/cvisionai/tator/pull/1487

**Comment by sbatchelder** [comment]
While waiting for the PR to go through, I'm trying out the django-shell route since indeed my client won't let me add to a DELETE request's body. Your steps worked fine until I ran into a version which also had STATES in it. Deleting the state through the REST API (without body{'prune':1}) is also not sufficient to then remove the version. 

```
>>> set=Localization.objects.filter(project=1,type=1,version=3)
>>> set._raw_delete(set.db)
8
>>> from main.models import State
>>> State.objects.filter(project=1,version=3)
<QuerySet [<State: State object (1703)>]>
>>> State.objects.filter(project=1,version=3).db
'default'
>>> set = State.objects.filter(project=1,version=3)
>>> set._raw_delete(set.db)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.ForeignKeyViolation: update or delete on table "main_state" violates foreign key constraint "main_state_media_state_id_9d6e0631_fk_main_state_id" on table "main_state_media"
DETAIL:  Key (id)=(1703) is still referenced from table "main_state_media".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 762, in _raw_delete
    cursor = query.get_compiler(using).execute_sql(CURSOR)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: update or delete on table "main_state" violates foreign key constraint "main_state_media_state_id_9d6e0631_fk_main_state_id" on table "main_state_media"
DETAIL:  Key (id)=(1703) is still referenced from table "main_state_media".

>>> set
<QuerySet [<State: State object (1703)>]>

```

**Comment by sbatchelder** [comment]
Figured it out, using `DELETE /rest/state/{ID}` REST page and `body:{prune:1}`.
Thanks!!

**Comment by bctcvai** [comment]
Excellent! I am guessing the `_raw_delete` was problematic on States; you got past it, but `qs.delete()` is slower but generally won't cause those same issues.
