### ISSUE TITLE
completely remove a user

### ISSUE THREAD

**Issue by duane-edgington** [cvisionai/tator#1515]
Hi. We are using Tator, and are relatively new to the tool. We have a user who forgot their password shortly after creation of their account. They want to keep their same email account. As an administrator, is there a way for me to completely delete a user and their password so this individual can start afresh?

**Comment by jrtcppv** [comment]
Hello, if you are a superuser you can visit http://yourdomain/admin and it will bring you to the Django admin console. There you can click on the `Users` model and you can modify or delete any user that is there. If you click on a user there is a link to a password reset form under the password section. Let me know if that works for you.

**Comment by jrtcppv** [comment]
@duane-edgington did the password reset work for you? Was going to close this issue if you are good to go.

**Comment by duane-edgington** [comment]
You can close the issue. 

In the end the user found their password before we could try your method. I did not have the authorization to do that method. 

Duane Edgington
