### ISSUE TITLE
Launch other applets from within an annotator applet

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#1522]
**Category**
Feature Request

**Problem**
Currently to switch between applets, the user must exit out of the applet and either right-click or use the side toolbar to open an applet. This can add more unnecessary UI interactions.

**Request**
Allow applets to be opened from other applets (e.g. close and dispatch an event to open another registered applet). This can save time and allow applets to coordinate with each other.

**Comment by marktaipan-cvisionai** [comment]
Only canvas applets will have this feature.

It is currently tricky to pass in the correct media in the multiview case and I'm not certain it makes sense to switch between menu applets. If that's the workflow, then it's likely those applets need to be combined into a single applet. From our experience menu applets tend to be unique to the project and generally aren't shared amongst multiple projects. If they were, it would make sense to keep them separate from a code sharing perspective like canvas applets. We can re-open this issue or open a new issue specific to menu applets if a use-case is defined and this feature is desired.

**Comment by jrtcppv** [comment]
Closed by #1623.
