### ISSUE TITLE
Favorites in favorites panel are unsorted

### ISSUE THREAD

**Issue by robertgodfrey** [cvisionai/tator#1534]
When a user has added many favorites, it becomes difficult to find a particular favorite because the favorites are unsorted. Displaying the favorites sorted alphabetically would solve this issue. 

![image](https://github.com/cvisionai/tator/assets/102856686/815d9baf-9da5-4b6e-9fff-34e17e65b828)

**Comment by jrtcppv** [comment]
This would be a good thing to implement, but for the time being I am wondering if you would find the Tator autocomplete feature useful - it allows you to start typing a species and then a search is performed on a taxonomy and the top results are suggested in a dropdown. The taxonomy can be one you define yourself in Tator or one served elsewhere such as WoRMS. There is a tutorial [here](https://www.tator.io/docs/developer-guide/working-with-annotations/define-a-label-tree) explaining how to define a label tree within Tator and use it for autocomplete, if you are interested in hooking up to another service like WoRMS let me know, we have integrated with a couple such services.

**Comment by robertgodfrey** [comment]
We do have the autocomplete set up and it is useful, just looking to save a few more seconds 😁

**Comment by jrtcppv** [comment]
@robertgodfrey Should be fixed in #1536, if you prefer to stick with releases it should be in v1.3.0.

**Comment by robertgodfrey** [comment]
Awesome thank you!
