### ISSUE TITLE
Localization resize more than once fails

### ISSUE THREAD

**Issue by sbatchelder** [cvisionai/tator#1572]
One of my users brought up an issue where resizing a Localization more than once fails to update the Localization. They sent me two video examples.
Is this reproducible on your end? 

https://github.com/cvisionai/tator/assets/44208509/e843be13-737e-47ba-a90d-b67f3d42bfa2

https://github.com/cvisionai/tator/assets/44208509/c5b46359-c826-4adc-b0d6-8f13aa98afa1

Version: `main` branch, commit 2d14432f7561625f261f6637e6ccd329991b0b17 , 2024-02-25

**Comment by jrtcppv** [comment]
@sbatchelder thank you for catching that, we were able to reproduce and will prioritize fixing this before releasing `1.3`.

**Comment by bctcvai** [comment]
This issue was resolved in #1573 and should no longer be occurring.
