### ISSUE TITLE
Transcode activity not showing from Activity Button (as stated in upload complete messaging)

### ISSUE THREAD

**Issue by ermbutler** [cvisionai/tator#1627]
<img width="620" alt="image" src="https://github.com/cvisionai/tator/assets/17165227/48fea879-3531-4a87-8dc8-c42287f66133">

If you upload a video, the complete message above is shown: "Upload complete! Monitor video transcodes with the "Activity" button." But the activity tab when visited shows no information about the transcodes.

1. User clicks "Close"
2. User can see Media gallery -> shows 0 media
- Clicks refresh, shows loading image thumbnail for uploaded video which is in transcode
3. **Click Activity button -> "No jobs in progress."**
- **Click refresh, still shows "No jobs in progress."**

**Comment by bctcvai** [comment]
`/rest/Transcodes` is used for transcode status.
