### ISSUE TITLE
Downloading metadata bulk and single could utilize existing dashboards

### ISSUE THREAD

**Issue by ermbutler** [cvisionai/tator#1632]
To improve the architecture used on the project detail page, we would like to deprecate the use of Stream Saver. As part of fixes for bulk media and single media downloads, we will also fix exporting by connecting existing, more robust export functionality through a product dashboard-like page.

**Comment by marktaipan-cvisionai** [comment]
Currently fixed on the rc/1.3.0 branch here: 29a9e02aa8571bf64b69213f262e40e7c54b783c

Won't close this until the RC branch is merged back to main

**Comment by marktaipan-cvisionai** [comment]
Not yet on `main`, but will close the issue.
