### ISSUE TITLE
Redraw and attribute updates are conflicting

### ISSUE THREAD

**Issue by ermbutler** [cvisionai/tator#1635]
Problem: When using redraw for a box localization for which I added a String value, I am losing the string value added during that session on page refresh

**Value gets set back to ""**
1. Create a localization
2. Edit an attribute from "" to "XYZ"
3. Use “redraw”
4. Entity browser still shows XYZ (looks ok)
5. Refresh,  Entity browser shows attribute as "", the previous value

**It is saving, but redraw is the issue because if you.....**
7. Visit page when value is ""
8. Update to XYZ
9. Refresh the page, and value is XYZ
10. Use “redraw”
11. Entity browser still shows XYZ
12. Refresh,  Entity browser still shows XYZ

**Doesn't just set it to "", it is the first value during session**
13. Visit page when value is already XYZ
14. Edit to “ABC”
15. Use “redraw”
16. Entity browser still shows ABC
17. Refresh,  Entity browser shows XYZ

Is this maybe related to a clean up activity that is bipassed because of this issue?
See: https://github.com/cvisionai/tator/issues/1634

**Comment by bctcvai** [comment]
May be fixed with #1364
