### ISSUE TITLE
bulk_patch_attributes doesn't update ES reliably

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#165]
Something happens on larger querysets to cause the psql database and ES to get out of sync.

**Comment by jrtcppv** [comment]
We should see if we can replicate this in the tator-py unit test `test_localizations.py`; currently it updates up to 10K localizations but when they are retrieved and checked the query is pure psql. We can add in a start=0 to force use of ES and see if the test still passes. We also don't test bulk patch on media.

**Comment by bctcvai** [comment]
It was over 10K media elements. Close to 40k. PSQL did update so the fetch
and serialization looked right. Not sure what the unit test does.

The search results were all wrong.

**Comment by jrtcppv** [comment]
This was caused by calling `bulk_patch_attributes` directly; to stay in sync, `TatorSearch().update(...)` must also be called to do the bulk update in ES.

**Comment by bctcvai** [comment]
I actually reproduced the problem again using the rest API directly. But I suspect it was because I got a compile error on the ES side of the house. 

`{
  "message": "RequestError(400, 'script_exception', 'compile error')",
  "details": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/rest_framework/views.py\", line 502, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/tator_online/main/rest/_base_views.py\", line 54, in patch\n    response_data = self._patch(params)\n  File \"/tator_online/main/rest/media.py\", line 135, in _patch\n    TatorSearch().update(self.kwargs['project'], query, new_attrs)\n  File \"/tator_online/main/search.py\", line 401, in update\n    conflicts='proceed',\n  File \"/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py\", line 84, in _wrapped\n    return func(*args, params=params, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/elasticsearch/client/__init__.py\", line 932, in update_by_query\n    \"POST\", _make_path(index, \"_update_by_query\"), params=params, body=body\n  File \"/usr/local/lib/python3.6/dist-packages/elasticsearch/transport.py\", line 358, in perform_request\n    timeout=timeout,\n  File \"/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/http_urllib3.py\", line 257, in perform_request\n    self._raise_error(response.status, raw_data)\n  File \"/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/base.py\", line 182, in _raise_error\n    status_code, error_message, additional_info\nelasticsearch.exceptions.RequestError: RequestError(400, 'script_exception', 'compile error')\n"
}`
