### ISSUE TITLE
Changing one activity value in a multi-activity states can result in setting all activity values to `false`

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#1684]
If a state has two activity booleans (Activity 1 and Activity 2), changing the value of Activity 1 results in both Activity 1 and Activity 2 being set to false. This is also saved to the database, so the edit is not saved.

**Comment by marktaipan-cvisionai** [comment]
Closed by 4d8ef9fe1a5e7de74628ae45fa4cffc423d41c76
