### ISSUE TITLE
Keyboard shortcut for rate control

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#17]
For workflows where lots of small videos need to be watched a rate control shortcut would be helpful, propose using up and down arrows

**Comment by marktaipan-cvisionai** [comment]
Added specific keyboard shortcuts for 1x, 2x, and 4x (1, 2, and 4 respectively). These are the rates supported by the onDemand playback.

Closed by 6cb18a5e3aa958b3d46e97a0ed5db53a5c38d0dd
