### ISSUE TITLE
CSRF issue on login (rc/1.3.0)

### ISSUE THREAD

**Issue by sbatchelder** [cvisionai/tator#1708]
Saw that VAST Support was added to rc/1.3.0 yesterday ([6ee01bb](https://github.com/cvisionai/tator/commit/6ee01bb53b0645e150e22b265a4de9942d3d763c))
Decided to try it out, and it seems to work/connect to out VAST backend properly, great. 

However, if I log out of my user account, I can no longer log back in. After submitting user credentials I get hit with a `Forbidden 403` `CSRF verification failed. Request aborted` error. 

Is this reproducible on your end?

![image](https://github.com/cvisionai/tator/assets/44208509/e944b288-babb-423c-aae7-d0f3dd25a193)

**Comment by jrtcppv** [comment]
Hi @sbatchelder , I just tried this on my compose deployment and was not able to reproduce. I tried deleting the `csrftoken` cookie while on the login page, and after reloading it was set again. Do you see the same behavior?

**Comment by sbatchelder** [comment]
Yes. On the login page I delete the csrftoken cookie, i reload the page, cookie is generated, I go to login, and I get the CSRF verification 403 error again.

**Comment by jrtcppv** [comment]
I was going through our changelog for 1.3.0 and came across this:

https://github.com/cvisionai/tator/pull/1608

I think with a proxied config we might need to shim something into that setting via an environment variable.

**Comment by sbatchelder** [comment]
Adding our specific site url to `CSRF_TRUSTED_ORIGINS` in `settings.py` did the trick!
Thanks Jon!!
