### ISSUE TITLE
Tune-up localization gallery

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#1780]
- Don't attempt to fetch a localization graphic if dimensions of a localization are not set.
- Limit maximum page size to 25 from 200.

**Comment by marktaipan-cvisionai** [comment]
We may just want to stagger the calls instead of just limiting to 25. If a user keeps cycling pages at 25 quickly, then one may likely run into similar performance issues when the page size is 200.

**Comment by bctcvai** [comment]
Adding a new endpoint to replace `rest/LocalizationGraphic` that avoids the database might help as well.

Basically the new endpoint will take a presigned URL and localization object; and run for authenticated users, returning the result. We will deprecate the existing endpoint and remove in 2.0

**Comment by bctcvai** [comment]
Closed via #1784
