### ISSUE TITLE
Add a way to use 'textarea' for string attributes

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#216]
Some string attributes are longer than others, and a text area may be more appropriate. 

Potential suggestion is to add a nullable 'options' or 'style' to the attribute type definition in models.py that can specify 'long' somehow. That way we don't have to have multiple 'string' dtypes that have different visual representation.

**Comment by marktaipan-cvisionai** [comment]
Closed by e6cc8e39320bcdd13d09393109b30d15ff8e4d18
