### ISSUE TITLE
Make cluster fails in tator-image

### ISSUE THREAD

**Issue by Kilill** [cvisionai/tator#22]
Trying to run make cluster fails after some time with:
`
Installed /usr/local/lib/python3.6/dist-packages/oauthlib-3.1.0-py3.6.egg
error: setuptools 39.0.1 is installed but setuptools>=40.3.0 is required by {'google-auth'}
The command '/bin/sh -c python3 setup.py install' returned a non-zero code: 1
Makefile:132: recipe for target 'tator-image' failed
make[1]: *** [tator-image] Error 255
`
Host: fresh install of Ubuntu 18.04LTS

**Comment by jrtcppv** [comment]
Thanks for bringing this to our attention, should be fixed on the latest master.
