### ISSUE TITLE
Entity browser real estate updates

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#223]
The entity browser is running out of real estate (both width and height) and needs to be expanded/cleaned up. Some ideas/suggestions to polish it up:

- Entity browser width could expand by some amount (maybe to 400px?)
- The "more" feature in the entity selector could toggle a second row below the entity label with the extra buttons going there
- Ability to toggle the frame panel (i.e. states with interpolation == latest and association == frame)
- Some of the projects have a large amount of fields. It would be nice to potentially limit the height of the attribute panel and also style the scrollbar so that it's more inline with the overall CSS theme (there is no CSS theme for the scrollbar right now)

This will most likely affect the following files:

- entity-browser.js
- entity-selector.js
- attribute-panel.js
- frame-panel.js

**Comment by BGWoodward** [comment]
Some additional UI cleanup suggestions:

- Make the right hand panel collapsible as in the analytics view 
- Group together top panel controls into context menus (e.g. link, screenshot, bookmark)
- Create more compact representations of the playback and resolution controls
- "Theater mode" to hide all UI controls and only view the video
- Right hand panel as a space for different "modules" customizable by project
- Ability to organize entity browser attributes into different groups and customize the location of them

**Comment by marktaipan-cvisionai** [comment]
Closed with f5639681529d17ad148aa165d924b27d4bd9c2e7
