### ISSUE TITLE
World-wide natural key for cloning idempotency

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#225]
Currently we use name for idempotency for most objects. Instead it would be nice to have a new field that encodes the origin host, primary key, and type that can be used for POST requests when creating clones. If this is not passed in a POST it would be generated server side.

**Comment by bctcvai** [comment]
Changed title to reflect it being a world-wide natural key (b64 string) rather than uuid.

**Comment by bctcvai** [comment]
This will be resolved in #723
