### ISSUE TITLE
Build fails in marshal-image 

### ISSUE THREAD

**Issue by Kilill** [cvisionai/tator#24]
`Error response from daemon: Dockerfile parse error line 7: COPY requires at least two arguments, but only one was provided. Destination could not be determined.`

Seems the COPY Line is not to happy about the escaped newlines, changing it to what i assume it should to be:

`COPY PyTator-0.0.3-py3-none-any.whl /PyTator-0.0.3-py3-none-any.whl`

makes that part compile

It then fails again in helms install:

`helm install --atomic --timeout 60m0s --set gitRevision=40547ce72d9873b42e87ad06c100aa62ed744868 tator helm/tator
Error: apiVersion "apps/v1beta2" in tator/charts/metallb/templates/speaker.yaml is not available
Makefile:110: recipe for target 'cluster-install' failed
make[1]: *** [cluster-install] Error 1
make[1]: Leaving directory '/home/kill/tator'
Makefile:104: recipe for target 'cluster' failed
`

Host: Fresh install Kubunutu 18,04 LTS

**Comment by jrtcppv** [comment]
@Kilill Let us know if you want help configuring your deployment once you complete the tutorial. We are still working toward a stable release of Tator and have not yet documented how to administer a deployment, including creating projects and defining metadata types.
