### ISSUE TITLE
ES Mappings do not encourage the same attribute name across different types within the same project

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#246]
This is not really a bug as much as something that should be aware as type manipulation happens. 

If project X creates a StateType called Foo with a string attribute called "Fred", and project X also has a LocalizationType called Bar with a string attribute called "Fred", both "Freds" are stored in a mapping called "Fred". This is OK assuming they are the same type, but problems could arise if "Fred" was in int in one type an a string in another. I would guess this would be more of a nuance if different types of strings were ever allowed.

**Comment by henxing** [comment]
https://github.com/cvisionai/tator/commit/c44fb33712efdb41df0acf090889945a76eb67e3 enforces attribute types of the same name (on different entity types) must have the same `dtype`, project-wide.
