### ISSUE TITLE
Unset DOCKERHUB_USER in Makefile fails build

### ISSUE THREAD

**Issue by Kilill** [cvisionai/tator#25]
Adding DOCKERHUB_USER=<dockbub_user> at the top fixes it

**Comment by bctcvai** [comment]
@Kilill : Thanks for the comment. 

We use that makefile variable from the environment variable, presumably set in `.bashrc`. We do that to support multiple deployment types --- some of our deployments use local docker registries, others are able to use dockerhub. For airgapped or isolated deployments this ends up looking like `hostname:port/username/<image_name>` where DOCKERHUB_USER is set to hostname:port/username. 

We are open to suggestions if that doesn't work for your environment.

**Comment by Kilill** [comment]
Maybe make a note of it the deployment docs that it might need to be set and what it needs to be set as for the local registry. 
and/or perhaps check for it not being set in the make file and make and fail with a warning. Could it default to something meaningful if its not set and there is a local registry ?

**Comment by jrtcppv** [comment]
The documentation for DOCKERHUB_USER was recently removed because of our migration to helm; it escaped me that we would still need it for pushing images, so I will definitely put it back into the docs. I think we could potentially default to DockerHub if this is not defined but I would want to throw a warning probably.

**Comment by jrtcppv** [comment]
Also at this point I think DOCKERHUB_USER is a bit of a misnomer... should probably be DOCKER_REGISTRY or similar.

**Comment by bctcvai** [comment]
We could split it into two variables DOCKERHUB_REGISTRY + DOCKERHUB_USER to be more precise --- the former is only required if you don't use dockerhub. It's just prepended before the username in the full image name so the push command goes to the specified registry. There may be yet another setting in docker somewhere to set a default remote registry --- not really sure without looking at the docs. 

At the end of the day; <host>/<user>/<image_name>, needs to be acquired.
