### ISSUE TITLE
Migrate media from disk storage

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#254]
Resource Migration
* Utility accepts project and optionally a section
* Search for Resource objects referencing media in that project/section
* Generate key based on organization/project/media/basename
* Upload file to S3 via boto3.s3.transfer
* In one atomic transaction, select all affected media and resource for update
  - For each Media, modify paths in `media_files` f
  - For Resource, modify `path` field
* Delete the file from EFS

Image Migration
* Utility accepts project, a field (one of file, thumbnail, or thumbnail_gif) and optionally a section
* Search for Media objects matching project/section and with non-null field
* Generate key based on organization/project/media/basename
* Open file in PIL and create a ImageDefinition that can be used to update the media
* Upload file to S3 via boto3.s3.transfer
* In atomic transaction, select media for update
  - Set selected field to None
  - Update appropriate role in media_files
* Delete the file from EFS

Original Migration
* Utility accepts project and optionally a section
* Search for Media objects matching project/section and with non-null original
* Generate key based on organization/project/media/basename
* Inspect file with ffprobe and create a VideoDefinition that can be used to update the media
* Upload file to S3 via boto3.s3.transfer
* In atomic transaction, select media for update
  - Set original field to None
  - Update appropriate role in media_files
* Delete the file from EFS

Database Migration
* Once the above migrations are complete, verify that NO media contains file, thumbnail, thumbnail_gif, or original
* Delete those fields from main/models.py and upgrade

Code cleanup
* Clean up all places in codebase that look for file, thumbnail, thumbnail_gif, or original

**Comment by bctcvai** [comment]
test plan might be to use some existing files we don't care about, to make sure it works before any broad-based script gets launched.

**Comment by jrtcppv** [comment]
I am actually thinking maybe we don't delete from EFS until the migration is complete, then instead of deleting files based on migrated database fields we would look at the `TemporaryFile` and `Algorithm` objects to see what we should keep then delete everything else, since those are the only EFS based files per project that should exist when we are done migrating.
