### ISSUE TITLE
make cluster fails after hanging in helm install

### ISSUE THREAD

**Issue by Kilill** [cvisionai/tator#26]
running: 

`helm install --debug --atomic --timeout 10m0s --set gitRevision=9a79bb9da5ed6219a8a7d4355770356852fc65f9 tator helm/tator`

manually gives:

`nstall.go:148: [debug] Original chart version: ""
install.go:165: [debug] CHART PATH: /home/kill/tator/helm/tator

client.go:87: [debug] creating 56 resource(s)
wait.go:52: [debug] beginning wait for 56 resources with timeout of 10m0s
wait.go:200: [debug] PersistentVolumeClaim is not bound: default/raw-pv-claim
wait.go:200: [debug] PersistentVolumeClaim is not bound: default/raw-pv-claim
wait.go:200: [debug] PersistentVolumeClaim is not bound: default/raw-pv-claim
wait.go:192: [debug] Service does not have IP address: default/nginx-svc
wait.go:192: [debug] Service does not have IP address: default/nginx-svc
wait.go:192: [debug] Service does not have IP address: default/nginx-svc
wait.go:192: [debug] Service does not have IP address: default/nginx-svc
wait.go:192: [debug] Service does not have IP address: default/nginx-svc
`

Until it times out. Is nginx suposed to run on some node ?

**Comment by jrtcppv** [comment]
I believe this is because kube is unable to bind the persistent volumes it needs. Did you set up the NFS server as in the tutorial? I'm not sure offhand if the share name must be /media/kubernetes_share/* as specified in the docs but we can probably make that configurable if you want to use a different path.

**Comment by Kilill** [comment]
Nice catch, fixed net permissions for NFS exports 
But that is not whats causing the install to hang indefinitely, this is:

wait.go:192: [debug] Service does not have IP address: default/nginx-svc

**Comment by bctcvai** [comment]
I am listing a few commands below which may help us figure out where it got hung up along with their rationale. They can be run in any directory by a user with ability to run `kubectl`. 

`kubectl get svc` --> Will output all the services, so we can see where nginx is if at all. It should be a service registered to at least 1 pod based on the values.yaml in the helm chart. 

`kubectl get pvc` --> Just to double check all the pv's are mountable by k8s. 

`kubectl get nodes` --> Sanity check on k8s cluster itself. 

`kubectl get pods` --> Queries all the pods running in the cluster (in the default namespace at least)

**Comment by Kilill** [comment]
Attached file with output ,containg one set before `helm --debug --install .....` and one while its running and complaining about nginx.
[kubelog.txt](https://github.com/cvisionai/tator/files/3821725/kubelog.txt)

**Comment by jrtcppv** [comment]
Looks like the assignable range of IP addresses for MetalLB is not on the same subnet as the load balancer IP. I would try changing that to:

```
  ipRangeStart: 192.168.127.220
  ipRangeStop: 192.168.127.224
```

This is why you are getting `<pending>` for `EXTERNAL-IP` when you use `kubectl get svc`.

**Comment by jrtcppv** [comment]
Also you should be able to apply that change with `make cluster-upgrade`.

**Comment by Kilill** [comment]
Reinstalled on a new machine (fresh Ubunut 18.04) and went through the deployment process from scratch so that no lingering kubernetes,docker and tator ghost should be present.
Did get a tad longer this time , still hanging in the install though.

It seems there are 3 pods that continuously are crashing: 
`pruner-deployment, sizer-deployment and submitter-deployment.`

helm --debug --install ..... reports:

`wait.go:209: [debug] Deployment is not ready: default/sizer-deployment. 0 out of 1 expected pods are read`

and once in a while:

`wait.go:209: [debug] Deployment is not ready: default/pruner-deployment. 0 out of 1 expected pods are ready`

attached the usual logs, and the output from `kubectl describe pod sizer-deployment
[log.txt](https://github.com/cvisionai/tator/files/3826765/log.txt)
`

**Comment by Kilill** [comment]
also adding the the container log for sizer-deployment
[sizer-deployment.log](https://github.com/cvisionai/tator/files/3826775/sizer-deployment.log)

**Comment by jrtcppv** [comment]
I believe now all that is needed is to run `make migrate`. This will set up the schema in your database using your gunicorn pod. We had this running automatically before in an init container but recently disabled that, so I will add this step to the documentation.

**Comment by jrtcppv** [comment]
I added post-upgrade and post-install hooks to do migrations and collect static files on the latest master. You can try just doing a `make cluster-upgrade` with the latest master, but `make migrate` will still work.

**Comment by Kilill** [comment]
Well. both those suggestions assumes that the tator-online is up and running, which is not the case since there are 3 pods that never comes online and therefore the helm --install .... tator never completes successfully.  To me it seems that the postgres database is never correctly initalized.
looking at the log for submitter-deployment (one of the 3 continlously restarting pods) this is a the top the **relation \"main_job\" does not exist** part says it all:

```
"Traceback (most recent call last):\n","stream":"stderr","time":"2019-11-10T14:18:31.858890523Z"}
{"log":"  File \"/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py\", line 84, in _execute\n","stream":"stderr","time":"2019-11-10T14:18:31.858907751Z"}
{"log":"    return self.cursor.execute(sql, params)\n","stream":"stderr","time":"2019-11-10T14:18:31.858911037Z"}
{"log":"psycopg2.errors.UndefinedTable: relation \"main_job\" does not exist\n","stream":"stderr","time":"2019-11-10T14:18:31.858913106Z"}
{"log":"LINE 1: ..., \"main_job\".\"pod_name\", \"main_job\".\"status\" FROM \"main_job\"...\n","stream":"stderr","time":"2019-11-10T14:18:31.858915224Z"}
{"log":"
```

Result of bot make migrate and make cluster-upgrade respectively,while helm --install is still running ie tator is semi functional

**make migrate**:
```
kubectl exec -it $(kubectl get pod -l "app=gunicorn" -o name | head -n 1 | sed 's/pod\///') -- python3 manage.py makemigrations
kubectl exec -it $(kubectl get pod -l "app=gunicorn" -o name | head -n 1 | sed 's/pod\///') -- python3 manage.py migrate
No changes detected
ESC[36;1mOperations to perform:ESC[0m
ESC[1m  Apply all migrations: ESC[0madmin, auth, authtoken, contenttypes, django_ltree, sessions
ESC[36;1mRunning migrations:ESC[0m
  Applying admin.0001_initial...Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "main_user" does not exist

```
Same but with killed tator install

**make migrate**:
```
tator@tator:~/Tator$ make migrate
kubectl exec -it $(kubectl get pod -l "app=gunicorn" -o name | head -n 1 | sed 's/pod\///') -- python3 manage.py makemigrations
kubectl exec -it $(kubectl get pod -l "app=gunicorn" -o name | head -n 1 | sed 's/pod\///') -- python3 manage.py migrate
error: unable to upgrade connection: container not found ("tator-online")
error: unable to upgrade connection: container not found ("tator-online")
Makefile:339: recipe for target 'migrate' failed
make: *** [migrate] Error 1

```
**make cluster-upgrade:**
Attached as file since a bit longish
[upgradelog.txt](https://github.com/cvisionai/tator/files/3828590/upgradelog.txt)

**Comment by jrtcppv** [comment]
Can you give me the output of just `make cluster`? It is complaining about no helm package existing. If that does not work I may need to make the migration hook pre-install rather than post-install.

**Comment by Kilill** [comment]
complete makelog attached, from a completely fresh install, added  --debug on the helm install step in the makefile
[makelog.txt](https://github.com/cvisionai/tator/files/3841037/makelog.txt)

**Comment by jrtcppv** [comment]
Thanks for the log. I am working on this and should have a fix soon.

**Comment by jrtcppv** [comment]
Ok @Kilill, give latest master a try. You may need to `make cluster-uninstall` or start with a fresh cluster. I'll wait until you get a successful build to close the issue.

**Comment by Kilill** [comment]
One step closer but still nope. 
removed all traces of kubernetes,docker registry and Tator clone. Reinstalled kubernetes, docker registry and recloned/initialzied Tator , added --debug to Makefile.

Looking at the log file from migrate-job it seems there is still some database errors:
```
{"log":"psycopg2.errors.UndefinedObject: type \"ltree\" does not exist\n","stream":"stderr","time":"2019-11-15T12:52:11.772142719Z"}
{"log":"LINE 1: ...base_ptr_id\" integer NOT NULL PRIMARY KEY, \"path\" ltree NOT ...\n","stream":"stderr","time":"2019-11-15T12:52:11.772144843Z"}
{
```
Attaching logs.gz (tar cvzf) file containing log file from Make (makelog.txt) 
and a copy of /var/log/containers at the time of failure.
[logs.gz](https://github.com/cvisionai/tator/files/3851633/logs.gz)

**Comment by jrtcppv** [comment]
Apparently I forgot to merge my branch with the fix into master, very sorry about that... that branch contains a commit that creates the LTree extension in the database. I just pushed out the merged branch on master and retested it so please give it another try. This time I would clear out the contents of the `migrations` NFS share before doing the install.

**Comment by Kilill** [comment]
aha, it now builds without errors and something is running according to make status.
Did a  `make collect-static` after build cluster that also when through without complaining.
But it doesn't looks like there is anything listening on port 80. 
webrowser returns connection refused, and checking with` netstat -ap`  theres no process listening on port 80. tried both localhost and the actual IP that was set for the `loadBalancerIP` in values.yaml. 

Attaching output from `make cluster`, the logs from /var/logs/containers (this time actual files and not soft links :-P), output from `make status`, output from `netstat -anp` and the` values.yaml 
[logs.gz](https://github.com/cvisionai/tator/files/3854635/logs.gz)
`used

Btw, docs says to do `npm install` it was not completely obvious that this has to be done **inside** the Tator directory, so that could either be mentioned in the docs or made part of the Makefile in the `make collect-static` step.

not sure if you want this ticket closed, seeing as it actually now builds without errors, and open a new one ?

**Comment by kristianmk** [comment]
Check port 443 as well; based on the manual I would assume that tator is using https (and try using the configured domain name in case the application is routing based on the name..)..

**Comment by jrtcppv** [comment]
@kristianmk is correct, Tator requires the use of https, however Nginx is configured to redirect http requests to https and it should be listening on both port 80 and 443.

Just to confirm, are you checking the load balancer IP address? The `values.yaml` file you posted earlier said it was set to `192.168.127.6`. You would also need to make sure that your domain is configured to point to that address, and that the domain has a certificate in `real-secrets.yaml`. These steps are covered in the first two steps of the tutorial; we use duckdns.org and letsencrypt.org for development purposes since they are free.

I will update the `npm install` instructions to specify it should be done inside the tator directory. We can keep this discussion here until you get a login screen. I opened #28 so you will have some guidance on what to do from there.

**Comment by Kilill** [comment]
Well, unable to build at all now with failure
```
Processing /PyTator-0.0.3-py3-none-any.whl
ESC[91mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe538e5e040>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pandas/
ESC[0mESC[91mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe539574610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pandas/
```
assuming some server somewhere is down, i guess it will come back online somewhen

in the meantime , Just a couple of questions, 

1. looking at the example values-devExample.yaml and values-production.yaml 
the `loadBalancerIp: 192.168.1.221` is within the range of `ipRangeStart: 192.168.1.220` -
  `ipRangeStop: 192.168.1.224` should that be the case? 

2. How does metalb use the ip's in the range ?

3. in real-secrets, i assume that that `TATOR_SECRET_SSL_BUNDLE` is the server certificate for for the ngnix server. But what is 'TATOR_SECRET_SSL_KEY' used for ? , i hope that this is not supposed to be the private key for the server certificate,..

**Comment by jrtcppv** [comment]
1) Yes, the `loadBalancerIp` must be within the range `ipRangeStart`-`ipRangeStop`.
2) MetalLB will accept external traffic on an IP within that range. The NGINX service template requests a load balancer with an external IP at `loadBalancerIp`, which is why it must fall within the assignable range. We could probably make the range exactly one IP address and it would still work for our purposes, as there is only one load balancer.
3) Yes `TATOR_SECRET_SSL_BUNDLE` is the certificate generated at `/etc/letsencrypt/live/<your-domain>/fullchain.pem` and `TATOR_SECRET_SSL_KEY` is the private key generated at `/etc/letsencrypt/live/<your-domain>/privkey.pem`. These are used to create Kubernetes Secret objects which are then mounted as volumes in the NGINX deployment (specifically at `/ssl/CertificateBundle1.pem` and `/ssl/tator.key` in the NGINX pod, respectively). Is this an insecure way to do this? We are open to suggestions on alternatives.

**Comment by kristianmk** [comment]
Some security guidelines here https://kubernetes.io/docs/concepts/configuration/secret/ . Based on the documentation, I am not sure if a really secure solution is possible with Kubernetes (read the last part about risks..). I am not too familiar with Kubernetes and Kubelets however...

Better partitioning with a separate host (node) for the security related kubelets could probably be a good idea, to avoid some of the issues mentioned here (this is only a few attack vectors): https://labs.f-secure.com/blog/attacking-kubernetes-through-kubelet/

**Comment by Kilill** [comment]
Since this machine is behind a firewall, and only accessible in the local net, Letsencrypt is not an option, and it will take some time to convince the sysadmin in question to relinquish the domains private key, so for now a self signed certificate will have to suffice. 

Anyways. i'm back to nginx not getting an ip address... and it seems not all pods are getting created in the install step, several seems to be hanging in ContainerCreating.  Thinking this was a possible docker problem cleaned out all traces of Kubernetes and Docker and restarted from scratch, still no ip to ngnix, something changed ? attached logs...
[logs.gz](https://github.com/cvisionai/tator/files/3864474/logs.gz)

**Comment by jrtcppv** [comment]
Based on the tator-metallb-speaker and tator-metallb-controller logs, it looks like MetalLB is having trouble assigning an IP address for the load balancer. I did notice that in `values.yaml` you have the NFS server set to the same IP address as the load balancer; typically the NFS server would be set to the IP of the host running the NFS container/service, and the load balancer IP would be an IP address that is out of the assignable range of any DHCP servers on your LAN and does not conflict with any IP address already assigned.

For an example, on my dev machine's network I have a router with a DHCP range from 192.168.86.100 to 192.168.86.200; therefore I give the load balancer a range 192.168.86.220-192.168.86.224 (so that it doesn't conflict with the DHCP range) and request a load balancer IP within that range (192.168.86.221).

**Comment by Kilill** [comment]
sorry but i no longer have the time to pursue this issue. Thanks for the effort though

**Comment by jrtcppv** [comment]
Totally understand. Thanks for all the testing you did, it was very helpful. Hopefully you can check back in once we've made a release.
