### ISSUE TITLE
Option to disable downloading media from project

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#260]
Need ability to limit downloading media files from project either via user permissions or top level project permissions

**Comment by jrtcppv** [comment]
If you set user permissions to anything below `Can Transfer` they should be unable to download media. Is this not the case? Project level download disable would be new capability though.

**Comment by jrtcppv** [comment]
Might have to caveat the above, downloads are not actually disabled but the UI option for download disappears. If we actually disabled downloads we would have to figure out how to let users still view streaming video. I believe @bctcvai mentioned possibly using DRM for that purpose.

**Comment by bctcvai** [comment]
DRM is probably the only option to ensure a user doesn't sneakily download streaming media. That being said, things like `youtube-dl` exist and work quite well, so I am not convinced its particularly ironclad.
