### ISSUE TITLE
Multiple kubernetes pods in Error state after host reboot

### ISSUE THREAD

**Issue by kristianmk** [cvisionai/tator#27]
After rebooting the host computer, multiple pods ends up in an Error state. The (single host) installation was (probably) working prior to the reboot, as make status looked good, and login, project creation etc. worked as expected. The installation is based on instructions from git revision 2f2e1da5f3f72ce9a8e1824fe81929e55bc6247b.

Any ideas for debugging this? 

After reboot:

NAME                                        READY   STATUS      RESTARTS   AGE
algorithm-deployment-9bb98b88b-2d5ww        1/1     Running     0          15h
daphne-deployment-6b6ccd87bd-rvdfh          0/1     Completed   0          15h
gunicorn-deployment-5b5759d8c4-l57vj        1/1     Running     0          15h
nginx-5f9695fbcd-lq6sr                      1/1     Running     0          15h
packager-deployment-775698f6b-rfz7p         0/1     Error       0          15h
pgbouncer-79bcc96869-fbp8s                  0/1     Error       0          15h
postgis-658d69cf-hxdch                      0/1     Completed   0          15h
pruner-deployment-7d9b66dcb4-pc2dn          0/1     Error       0          15h
sizer-deployment-669f6f5db4-zzbfp           0/1     Error       0          15h
submitter-deployment-57db476b57-ndkvl       0/1     Error       0          15h
tator-metallb-controller-554df64cd9-4wjpg   0/1     Error       0          15h
tator-metallb-speaker-v5bwp                 1/1     Running     0          15h
tator-metrics-server-64ccb9f49f-6gkw8       0/1     Error       0          15h
tator-redis-master-0                        1/1     Running     0          15h
tator-redis-slave-0                         0/1     Completed   0          15h
tator-redis-slave-1                         0/1     Completed   0          15h
transcoder-deployment-fc497f58b-vqf8p       0/1     Error       0          15h
tusd-deployment-675d5bfb4c-f8w7x            0/1     Error       0          15h

**Comment by jrtcppv** [comment]
Can you please post the output of these commands:

```kubectl describe pod daphne-deployment-6b6ccd87bd-rvdfh``` 
```kubectl logs packager-deployment-775698f6b-rfz7p```
```kubectl get deployment.apps```

Basically if the pod state is `Error` let's look at `kubectl logs`, if it is `Completed` let's look at `kubectl describe`. Also want to check the state of your deployments. I have not had issues with the pods coming up after reboots so this is a new one to me.

**Comment by kristianmk** [comment]
The nfs server failed because of a typo in my /etc/modules file. After fixing it and rebooting, all pods seems to be healthy. 

Thank you very much for useful information on how to find the relevant logs; describe pod listed a lot of mounting errors, and `docker logs nfs3` showed me the exact problem.

**Comment by jrtcppv** [comment]
No problem! Glad it was an easy fix.
