### ISSUE TITLE
Fix disappearing drawn localizations

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#270]
There are somewhat intermittent cases where drawn localizations visually disappear on the canvas - but are still selected. If the canvas is refreshed they generally reappear but this should be fixed.

**Comment by bctcvai** [comment]
Just doing a pulse on whether this is reproducible

**Comment by marktaipan-cvisionai** [comment]
Closed with 9afa4855efd6adb636f58283421f481714226d35

**Comment by marktaipan-cvisionai** [comment]
Needs revisiting since this had other bugs with disappearing localization boxes

**Comment by marktaipan-cvisionai** [comment]
Closed with b8bd655cea5001a5d89780525ce27dd3b4fff505
