### ISSUE TITLE
Default version consistency

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#278]
Add a foreign key to a default version (on_delete=PROTECT) in Project models.
* Make this settable via project configuration page
* When videos are shown in the UI, it should display this version unless there is a version with the user's name
* When annotations are created programmatically, they should be assigned to the default version unless otherwise specified

**Comment by bctcvai** [comment]
User-level Default version per project can be stored in the membership object. Mutable by user or admin.
