### ISSUE TITLE
Write documentation for deployment administration

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#28]
Currently administration steps are not documented anywhere, add a new readme for this.

**Comment by kristianmk** [comment]
Will this include basic steps to get a project configured using the Django admin interface? That would be really helpful.

I started with a group, a user, a project, a full control membership for the user into the project and a Jpg image Entity type. This works partly, as I can upload images and they are listed in the project. But it is not possible to view/inspect a specific image. The Firefox "loading" symbol starts spinning as soon as I try to open an uploaded image, and nothing happens. I probably need to add something more to the project configuration..?

**Comment by jrtcppv** [comment]
Yes, this will include steps to configure projects including media types, annotations and metadata.

We need to put this in the documentation somewhere, but our testing currently only includes Chrome. Last I checked Firefox actually does support the web standards we need (WebGL 2, Service Workers, Custom Elements), so off-hand I am not sure why it is not loading. If Firefox is a required browser for you feel free to open a separate issue, otherwise I would give Chrome a try.

I should also note that some browsers will not work without a major rework, namely Edge/Explorer (no custom elements, although that is being implemented on Edge) and Safari (no WebGL 2; eventually we may transition our player to WebGPU which Safari will support).

**Comment by kristianmk** [comment]
WebGL 2 was not available in the browser. It looks like it was a Chrome-blacklisted or buggy graphics driver, after upgrading the driver, it works with Chrome.

Annotation tools are greyed-out however, as expected based on your previous comment.

**Comment by jrtcppv** [comment]
Took a crack at this under `Administer a deployment` on the front page. Feel free to open another issue if anything is unclear.
