### ISSUE TITLE
File download fails

### ISSUE THREAD

**Issue by kristianmk** [cvisionai/tator#30]
A minor issue regarding file download. When downloading "metadata" or "section" for a dataset, the download always fails with 403 forbidden.

The packager seems to produce the zip file successfully, but the permissions could be wrong (owned by root but readable for others). My user requesting the download is assigned all possible permissions (but no staff status).

The installation should be according to the latest manual, on a single host/node.

**Comment by jrtcppv** [comment]
I was able to reproduce this issue in my dev environment. Hopefully I can get a fix in pretty quickly, I suspect it's not too complex.

**Comment by bctcvai** [comment]
I isolated the issue for new packages. In the event you are attempting to access old packages; you'd want to run `main.util.movePackagesToProjectDirectories()` from a gunicorn-shell 

Specifically:
```
host shell> make gunicorn-bash
gunicron shell> python3 manage.py shell
django python shell > from main.util import *
django python shell > movePackagesToProjectDirectories()
```
