### ISSUE TITLE
Allow unspecified localization colormap in project settings

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#300]
There should be an option to not specify the colormap for localizations. Not having a color map specified enables the default annotator behavior.

**Comment by ermbutler** [comment]
@marktaipan-cvisionai Do you know if this is still a problem? I feel like this might have been covered with other work...

**Comment by marktaipan-cvisionai** [comment]
Good catch, looks like the colormap isn't being set anymore when the default is selected. Closing issue.
