### ISSUE TITLE
Boolean attribute controls don't refresh on undo operation

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#31]
If a boolean attribute is set, but then undone, the controls remain as though it is set. This is rectified after a refresh (frame seek or move); but if another set is attempted duplicate state entries can be inserted into the database.

It's possible other attribute editing fields suffer the same problem.

**Comment by ermbutler** [comment]
The data seems to be refreshed completely and this error is not still present.

Changing a boolean from Yes -> No then undo to Yes - working
Changing a boolean from No -> Yes then undo to No - working
