### ISSUE TITLE
Media archiving capability

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#312]
To save on storage costs, we need the ability to archive media. Archiving actions should be available through the UI. Archiving results in the following:
* If done via UI, the user should receive a warning that this action will result in being unable to access media for annotation for at least N days (180 if using deep archive)
* After confirmation, media is moved to deep archive (or possibly other storage tier) after a period of time (a week seems appropriate)
* Media is no longer accessible for annotation in the UI, however it can be seen in the project detail view and can still be found in searches/queries
* Media can be filtered with an `archived` REST parameter

**Comment by henxing** [comment]
Ok, so I see this as requiring a handful of somewhat-intertwined features:

**Comment by henxing** [comment]
Ok, so I see this as requiring a handful of somewhat-intertwined tasks:

1. Add `archived` flag to `Media` db
1. Add `archived` parameter to `Medias` endpoint (on a `GET` operation)
1. Add ability to archive media from the UI
1. Add cron job that archives media with a newly set `archived` flag

1 and 2 seem straight forward. 3 could be done a few ways, like adding an archive option in the dropdown menu on individual media or the section/search dropdown menu. 4 should probably be done the same as the prune operations that handle the `deleted` media, but the questions I still have are where does the media go and how is the media's location stored once it's archived? Maybe the cron job also detects media that has it's archived flag reset to `False` and somehow pulls it out of deep storage?
