### ISSUE TITLE
Change full screen mode to F11 equivalent

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#320]
Making the entity browser disappear is not helpful, instead make it the equivalent of pressing F11

**Comment by bctcvai** [comment]
```document.body.requestFullscreen()``` will do the same thing as F11 --- we might want to keep the code to hide the entity browser around. 

If we truly wanted full screen video; that is also 'possible' via the console, hit play and then type ```tator_video.requestFullscreen()``` to see the future.
