### ISSUE TITLE
Saving an existing type in project settings should only patch modified fields

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#350]

**Comment by ermbutler** [comment]
I am going to test this now -- I think there were some exception to this that required scheme update and that those are now handled.....

**Comment by ermbutler** [comment]
- [ ] Project 
- [ ] Media Type
- [ ] Localization Type
- [ ] Leaf Type
- [ ] State Type
- [ ] Membership
- [ ] Version
- [ ] Algorithm

**Comment by ermbutler** [comment]
Localization Type - sending line_width: 3 with all edits
Versions - sending "_number"
Algorithm - possibly sending all because they're required? todo check
Membership - todo test
