### ISSUE TITLE
Explicitly nullable attributes

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#364]
explicit nullable attributes, fill everything else with a default, and a type should have a default default if none is provided (or we don't enforce providing one)

**Comment by jrtcppv** [comment]
Explicit nullable may be bad, but default defaults should be implemented.

**Comment by bctcvai** [comment]
This is OBE by the v1 work. Attributes can now be reset to default or set to NULL via the `PATCH` operation.
