### ISSUE TITLE
Add human readable names into settings page

### ISSUE THREAD

**Issue by ermbutler** [cvisionai/tator#368]
Adding the name in addition to ID would make it easier to see what is being edited, and also is more user readable. Some users still could use the ID as a key for what they're editing but make it secondary through styling, color/size.

Where?

- The headings for an opened type or membership currently only show the ID.
- Some modals (which use responses from the backend)

Suggested edit:
{Entity Type} | {Name} (ID {id})

examples:
**Media Type | Test_images** (ID 46)
**Membership | Username** (ID 45)

**Comment by jrtcppv** [comment]
Closed by 991fa266782737ff48cc101ac9d98a7b79d69911.
