### ISSUE TITLE
Upload dialog

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#374]
Add modal upload dialog for web uploads. It should include the following:

* Section (dropdown, defaults to currently selected)
* Media type (dropdown)
* Media attributes (set on all uploaded media)
* Directory upload (checkbox, default No)
* Idempotent (checkbox, default No)

**Comment by ermbutler** [comment]
Moving these three criteria to their own tasks:
* Media attributes (set on all uploaded media) 
* Directory upload (checkbox, default No) #1889
* Idempotent (checkbox, default No) #1361
