### ISSUE TITLE
Track selections should be indicated for the lifetime of the track

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#40]
Currently only the first frame in a track is colorized as being selected, it would be helpful if the selection indication was shown for the entire track

**Comment by bctcvai** [comment]
1. The `attribute-panel` class should send a 'select' event like in `entity-selector` (on the track)

Attribute-panel:
https://github.com/cvisionai/tator/blob/0ea0846c5009e5ba1577e1a09f4ef4f52b5e8885/main/static/js/annotation/attribute-panel.js#L115

2. select event should contain a frame hint to allow `annotation.js` to select a track not at the start of the track as currently implemented. Example send from `entity-selector`:
https://github.com/cvisionai/tator/blob/0ea0846c5009e5ba1577e1a09f4ef4f52b5e8885/main/static/js/annotation/entity-selector.js#L234-L245
