### ISSUE TITLE
checkReady timer is getting stale

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#497]
Intermittently, the check ready timer in the video player goes stale causing the UI debouncing and underlying interlock logic to allow a play event when the buffers are not ready. It's likely a hang up in the state machine in general.

**Comment by bctcvai** [comment]
This appears to be fixed, but the interlock on multi is still allowing a play to commence before buffering. Now that the playing is "best effort" the playability determination can be tuned up a bit.

**Comment by marktaipan-cvisionai** [comment]
OBE - appears to have been solved with the animated svg problem.
