### ISSUE TITLE
Allow for external registration of algos/dashboard files

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#500]
When things like yaml or html files are registered in the platform, allowing an external registration from a git repo may be useful. For workflows, the git latency may not be a big deal. For UIs, some kind of 'update me' logic may be better (storing what githash is currently active)

**Comment by jrtcppv** [comment]
This functionality could likely be implementing by having the backend communicate with the code repository rather than dealing with CORS in the front end.
