### ISSUE TITLE
Fetching project icon from 3rd party resource can cause projects endpoint to hang

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#539]
If the 3rd party resource misbehaves there is an undefined behavior in the projects endpoint. This is mostly noticeable because project A's storage issue effects the listing of projects B, C and D. Likely the project listing of A will be degraded if the storage server is acting up. 

That being said, a couple of solutions to the specific problem of "issue leakage": 

-  Project thumbnails are always cached on "reliable" storage (or at least the same thing)

-  There is a timeout in accessing 3rd party resources (e.g. ~200 ms) in which case a sensible default is placed in if the timeout elapses.

**Comment by jrtcppv** [comment]
We fixed this with the first solution suggested.
