### ISSUE TITLE
Audio playback stutters

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#543]
Audio stutters during playback. Specifically it'll repeat a small segment of audio (e.g. if words are spoken, words are repeated every so often). This behavior was observed in the single video player and when using either the on-demand playback buffer or the scrub buffer.

**Comment by marktaipan-cvisionai** [comment]
It appears this problem is related to 60Hz videos. Changing the problematic videos to 30FPS seems to have fixed the audio sync issues. This issue is worth keeping around, but the priority is probably not high since there is a work around.

**Comment by bctcvai** [comment]
Resolved in #672
