### ISSUE TITLE
Inconsistent UI controls

### ISSUE THREAD

**Issue by BGWoodward** [cvisionai/tator#57]
Some controls when expanded, are unable to be unexpanded again. For instance, in videos with tracks, if you click the ellipsis button to expose the trash icon, there's no way to unexpand that without a reload

**Comment by bctcvai** [comment]
Did we want to decide if a confirm makes sense on delete? Or are we OK with ctrl-Z(undo) being the rectification to whoops I hit the trash can icon?

**Comment by marktaipan-cvisionai** [comment]
Closed by 57c200dc76dd332af97582be7399372fc6d81f58

- Fixed the vertical ellipsis problem (open/expand works on all localization types)
- Fixed not being able to use the "back" button on tracks when one was selected
- Fixed extra line being drawn when resizing boxes if the user overlapped during the drag
