### ISSUE TITLE
Cannot update algorithm manifest from project settings page

### ISSUE THREAD

**Issue by henxing** [cvisionai/tator#574]
## Steps to reproduce
1. Go to algorithm on project settings page
2. Click Choose File and select a new manifest
3. Click Save at the bottom of the page

## Expected behavior
Success message and project manifest updated

## Observed behavior
The following error message and the project manifest was not updated
![image](https://user-images.githubusercontent.com/8549603/148836160-07a6b047-6ac8-4ef5-a4ee-49aed25959e2.png)

**Comment by ermbutler** [comment]
@henxing do you know if this is still a problem?
