### ISSUE TITLE
Allow GL 1.0 usage in video player

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#60]
Add ability to support webgl 1.0 instead of webgl 2.0 -- potentially support both still with browser conditional checks, mostly for the MSAA switch. Both versions of webgl support the older shader language, we can select the latest webgl available.

1.) Convert shader to v100 language (see on goto_webgl1 branch)
2.) Convert MSAA logic from webgl 2.0 render buffer to potentially render to texture route.

**Comment by jrtcppv** [comment]
OBE, look at webGPU when it gets implemented. Sorry Safari users.
