### ISSUE TITLE
`rest/EntityMedias` endpoint crashes on large set

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#65]
Appears a bug was introduced to cause slow accesses to this endpoint

**Comment by jrtcppv** [comment]
suspect this is related to hosting somehow, this URL succeeds:

https://www.tatorapp.com/rest/EntityMedias/5?format=json&attribute=tator_user_sections::Videos%20(Fall%202018)&start=0&stop=1000

whereas this fails:

https://www.tatorapp.com/rest/EntityMedias/5?format=json&attribute=tator_user_sections::Videos%20(Fall%202018)&start=0&stop=10000

**Comment by jrtcppv** [comment]
Closed by 153e274687875229abcc8889f82fafba1fa3a02c.
