### ISSUE TITLE
Change filter interface to use ES exclusively

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#654]
The project-detail and analytics filtering interface utilizes some of the media/localization/state endpoint parameters (e.g. dtype). This allows an "OR" operation when others are implicitly "AND". It's suggested that we use the search fields exclusively (i.e. use ES lucene search strings exclusively). This would affect tator-data.js.

**Comment by marktaipan-cvisionai** [comment]
In addition to this, it makes sense if there are multiple of the same condition (e.g. multiple sections listed), that implies an OR command for that group. Here's an example:

Condition: Media section == "Section A"
Condition: Media section == "Section B"
Condition: Media dtype == "image"
Condition: Localization dtype == "Box"

Resulting string: (_section:"Section A" OR _section:"Section B") AND _media_dtype:"image" AND _localization_dtype:"box"

**Comment by bctcvai** [comment]
This is OBE by ES phase out.
