### ISSUE TITLE
ES fails to index datetime fields

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#685]
Unless a specific string representation is given for a datetime attribute, it will fail to be indexed in elasticsearch. Add a reformatting function for datetime attributes that will put it into[ one of the formats that ES works with by default](https://stackoverflow.com/questions/69210359/elastic-search-failed-to-parse-date-field-with-format-strict-date-optional-time).

**Comment by bctcvai** [comment]
There is probably limitations on what string inputs automagically will convert from what is a string in the attribute JSONB field to an indexed datetime. Some testing I did covered what I considered to be common usages:
YYYY-MM-DD and the full-up YYYY-MM-DDTHH:MM:SS did what you'd expect.
