### ISSUE TITLE
State POST endpoint should require frame param for frame-associated states

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#687]
It's currently possible to post a null for the frame parameter in the /states/POST endpoint even if the state spec associated with a frame-associated type. The endpoint should error / prevent this from occurring to prevent problems downstream (e.g. analysis and UI expecting frame numbers filled out).

**Comment by henxing** [comment]
Closed by fe64a229c19c7ce8506de28fa138d79a524c475e.
