### ISSUE TITLE
Idempotency checks for transcode workflow

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#688]
Currently if on resolution fails to transcode, other resolutions that succeed will be uploaded multiple times when the transcode workflow retries. Need to check if a file already exists in the `Media` object with the same `bit_rate`, `size`, `resolution` and if so do not upload it or patch the media object.

**Comment by jrtcppv** [comment]
For all current use cases only `codec` and `resolution` are sufficient for an idempotency check, so just use those. This will allow us to do the check at the start of the workflow to avoid retranscoding as well as reuploading.

**Comment by bctcvai** [comment]
@jrtcppv  This appears to be a resolved issue.

**Comment by henxing** [comment]
@bctcvai I'm actively working on this, but in the `tator-py` repo.

**Comment by henxing** [comment]
Implemented in commit [5cd5a1f13039298a88b36995a067798ab00028fb](https://github.com/cvisionai/tator-py/commit/5cd5a1f13039298a88b36995a067798ab00028fb) in the `tator-py` repo.
