### ISSUE TITLE
Have the ability to expand the photo on the right panel when in localization gallery view 

### ISSUE THREAD

**Issue by Giovanna43** [cvisionai/tator#738]
This will prevent you from having to click on each image separately when verifying wether localizations are neatly around an object. This would make reviewing or verifying images go a little quicker

**Comment by ermbutler** [comment]
A draggable width side panel for localizations gallery is going to be in the next release.

**Comment by ermbutler** [comment]
This is live. Part of [Release 0.2.20](https://github.com/cvisionai/tator/releases/tag/0.2.20)
