### ISSUE TITLE
Change case sensitivity in the search box

### ISSUE THREAD

**Issue by Giovanna43** [cvisionai/tator#741]
Currently, when you select the search filter “includes” in the modifier box, it’s case sensitive. You have to do separate searches to get images for the same animal name (e.g. **L**eopard **S**hark vs **L**eopard **s**hark vs **l**eopard **s**hark) each of these searches populate localizations. This depends on how the localizer creates the label.

**Comment by jrtcppv** [comment]
@bctcvai is this addressed by the index manager/search rework?

**Comment by ermbutler** [comment]
@jrtcppv or @bctcvai following up on this request.

**Comment by bctcvai** [comment]
Thanks Erin. I did change the default to case insensitive for v1.0.0 searches (by default, exposing both IIRC). We can consider the feasibility in a nearer term release too.

**Comment by bctcvai** [comment]
This has been  resolved  for awhile,  but we forgot to close the issue. `Includes` in the filter UI now defaults to case insensitive searches.
