### ISSUE TITLE
Merging Analytics Localisation and Correction gallery views

### ISSUE THREAD

**Issue by sbatchelder** [cvisionai/tator#751]
The analytics Localisations and Corrections views share enough similarities that their functionality could be merged to a single review view. This one view should have the same shared features (Gallery view+pagination, Filter options, Run Algorithm, Aspect vs. Fill, etc). The following functionality would be similar to those found on the current Localisation and Correction pages:

* No selection -  full gallery view
* Single localisation selection - right-side panel slides out as seen in current Localisation page. Attributes should be unlocked/editable by default (an edit-lock button can still be available as on current Localisations page). Features like showing the parent video frame and parent media details should be kept. 
* Multiple localisations selected - single-view right-side panel should slide-back/hide and bulk-edit bottom panel should slide up exposing the bulk-edit interface, as seen on the current Correction view
* Localisations should all have a checkbox in the upper left as seen on Correction view
* When a checkbox is checked, bulk edit mode is engaged. Shift-clicking a localisation will also trigger this mode
* When a single image is clicked _not_ on the checkbox, selection reverts back to single selection mode

**Comment by jrtcppv** [comment]
This is along the same lines as #740; @ermbutler can we take a look at the technical effort required for this? Also need to think about whether planned expansions of the two views would go against the grain in merging them.

**Comment by ermbutler** [comment]
There is now a button in the place as the "corrections" logo (top bar) to toggle you back to the "localizations" view (four square icon). There is also a text link. In addition, I've added back the ability to view the localizations panel in the corrections view, so you can see the localization and details more (includes the drag-to-expand panel) within corrections view. This is live. Part of [Release 0.2.20](https://github.com/cvisionai/tator/releases/tag/0.2.20)
