### ISSUE TITLE
Evaluate the Media and Section download code

### ISSUE THREAD

**Issue by ermbutler** [cvisionai/tator#756]
There is a 403 when getting information like media size which has not worked, and was not interupting download. This should be looked at to see why we're doing this - Can it be removed or fixed?

Second, the download code is relying on StreamSaver.js which the [team appended "(legacy-ish)" to the name in github in July 2021](https://github.com/jimmywarting/StreamSaver.js/commit/3955638d238cfca132e2a3d7c3427424cda930f5). Does  their updated repo meet our usecase? Or, is current code still doing fine, and doing what we need?

FROM: https://github.com/jimmywarting/StreamSaver.js
"... Don't worry it's not deprecated. It's still maintained and i still recommend using this when needed. Just want to let you know that there is this new native way to save files to the HD: https://github.com/whatwg/fs which is more or less going to make FileSaver, StreamSaver and similar packages a bit obsolete in the future, it'still in a experimental stage and not implemented by all browser. That is why I also built [native-file-system-adapter](https://github.com/jimmywarting/native-file-system-adapter) so you can have it in all Browsers, Deno, and NodeJS with different storages"

**Comment by bctcvai** [comment]
Suggest we utilize this, or some library that 

https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API or the "ponyfill" identified in your post: https://github.com/jimmywarting/native-file-system-adapter

**Comment by jrtcppv** [comment]
Closed by #1496.
