### ISSUE TITLE
Filtering media on enum returns different counts with and without `force_es`

### ISSUE THREAD

**Issue by henxing** [cvisionai/tator#761]
After adding a new possible value to an enum attribute, the count of media with the enum attribute set to a particular value (that already existed before adding the new value) is different when the query is supplied with `force_es=1` versus `force_es=0`.

1. Confirm that adding the enum value is a cause
2. Create minimum steps to reproduce
3. Determine if there are more causes or if this is the root cause
5. Fix and test

**Comment by jrtcppv** [comment]
OBE'd by #915.
