### ISSUE TITLE
Analytics filter not being applied to newly edited localisations 

### ISSUE THREAD

**Issue by sbatchelder** [cvisionai/tator#769]
On Correction view, after editing a localization such that it no longer qualifies for the current filter parameters (eg changing it's class), reloading the page or re-running the search will incorrectly still display the modified localization. To get desired result, user must perform a different filter, then re-run the original filter before the modified localization is correctly not-displayed.

**Comment by ermbutler** [comment]
Still following up for reasons for this on our side. But, TLDR; Task for this issue is:

- Review the logic for corrections view "bulk caching" and allow it to "re-apply" of a same search

**Comment by sbatchelder** [comment]
Hi Erin, I forgot to get back to you on this ages ago. 

So yes, it is for a large set of localizations.

Here is an example where that first image's class was changed, but it still appears in it's previous class search AFTER having re-run the search. Note it says fecal_pellet_long and not fecal_pellet_blob (sorry for this terrible example).

Refreshing the page after a classname change (under current conditions anyways) seems to work fine :)

![image](https://user-images.githubusercontent.com/44208509/189960612-9d02550c-6426-48b6-aa65-d038cc5513aa.png)
