### ISSUE TITLE
Modifying Enum attribute of a Localization fails on the Project Settings interface.

### ISSUE THREAD

**Issue by sbatchelder** [cvisionai/tator#780]
Modifying Enum attribute of a Localization fails on the Project Settings interface (see images below)

I've found that the only reliable way to do this is view the REST API.

![image](https://user-images.githubusercontent.com/44208509/179051102-c3b9884c-8203-4f81-a903-473615130d8e.png)

![image](https://user-images.githubusercontent.com/44208509/179051177-0fb6c489-19e7-4d15-b48e-0107d39cfa1e.png)

**Comment by henxing** [comment]
It seems that the specific circumstances were adding an enum choice when there is no default choice selected. PR #845 addresses this and the change will be live on https://earlyaccess.tator.io once it has been merged.
