### ISSUE TITLE
Feature: "is-not" Filter option `!=`

### ISSUE THREAD

**Issue by sbatchelder** [cvisionai/tator#785]
It'd be nice to be able perform filter queries where `!=` is an option alongside `==`

Our use-case is to find all localizations who's `_modified_by` is NOT `user_x` 

This feature would probably also be handy to include in the media gallery filter view too.

**Comment by bctcvai** [comment]
On the `dev/v1.0.0` branch we did an overhaul of the search and filtering capabilities. On that release, the underlying REST interface supports "is-not" and combinatoric logic like AND as well as OR. 

In the filter UI component, I added "Is not equal to" as a filtering option, but we haven't added the complexity of being able to group by OR or AND graphically yet.

**Comment by jrtcppv** [comment]
Implemented as of 1.3 (filter dialog says `Is Not Equal`)
