### ISSUE TITLE
Entity type selection no longer persist when clicking next

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#80]
From Kenny: In the past I was clicking the next file and I would go to the Detection Pair window that showed the number of unknowns which I would click on. Now, when I click the next file button, I go to the Annotation window where I have to click on Back then Detection Pair whick takes me to the Detection Pair window. Everything works the same - just need to click on a few extra buttons.

**Comment by bctcvai** [comment]
Commit e394624bc should resolve this; would like confirmation is possible.
