### ISSUE TITLE
Player error: Array buffer allocation failed

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#801]
Intermittent issue in video player causes video to not load. Current workaround is restarting the browser and/or machine.

![image (3)](https://user-images.githubusercontent.com/7937658/182473340-a981e6ad-7f8b-42b9-857c-f2351115ba02.png)

**Comment by bctcvai** [comment]
Fixed in 6b78f4f1adf6d07c27861c785ef7214ede3813d6. If in the future an array buffer fails like this, its similar to a malloc() failing. Waiting for garbage collection and seeking again should work; but the underlying buffer mismanagement was addressed that likely contributed here.
