### ISSUE TITLE
Investigate minio tiering for upload bucket

### ISSUE THREAD

**Issue by henxing** [cvisionai/tator#860]
Minio supports [object transition](https://min.io/docs/minio/linux/administration/object-management/object-lifecycle-management.html#id2), or "tiering", where a lifecycle rule can automatically move an object to a remote, S3-compatible object store. Investigate using this for the upload bucket on the cloud deployment, where the "live" tier is our own minio instance and the "backup" tier is an S3 bucket (configured with some sort of archival storage class, like GDA or IA).

**Comment by jrtcppv** [comment]
Recommend deleting or using cloud storage.
