### ISSUE TITLE
Policy-based project membership

### ISSUE THREAD

**Issue by henxing** [cvisionai/tator#900]
Managing individual users' project memberships (both at creation and ongoing) is currently a very manual process, requiring manual addition in all cases. Other service providers have a concept of security policies, where permissions can be granted to a policy and users are assigned one or more policies to manage their access permissions. This should include the ability to specify "wildcard" permissions, meaning access to all projects, current and future, in an organization.

**Comment by bctcvai** [comment]
This will be a component of #1096 

The intersection with this is two-fold: 
- Similar to a umask on linux, the default permission of a row-based security element needs to be configurable. 
- With row-based security members of an organization can be granted access to resources automatically.
