### ISSUE TITLE
POST requests should have attributes in an `attributes` sub-object

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#920]
For `Localization`, `State`, `Leaf`, and `Media` objects, the attributes in a `POST` request should go in a `attributes` sub-object as opposed to being in the top level object. This is for consistency with the objects returned from `GET` requests and bodies of `PATCH` requests.

**Comment by marktaipan-cvisionai** [comment]
It would be worth checking to see if this should be applied to other JSON-related fields (e.g. `media_files` in `Media` objects)
