### ISSUE TITLE
Allow version update in state patch endpoint

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#929]
Developers currently cannot move a state from one version to another using the State patch endpoint. Add this to the `update_spec` and investigate if this is needed in other similar endpoints.

**Comment by bctcvai** [comment]
@marktaipan-cvisionai , this is hit here https://github.com/cvisionai/tator/pull/723/files#diff-29356488b361f02b938a4ba839e1c40470d0ca5241b795c2b75a932d46900761

#723 is being combined with #915

**Comment by bctcvai** [comment]
@marktaipan-cvisionai , this is hit here https://github.com/cvisionai/tator/pull/723/files#diff-29356488b361f02b938a4ba839e1c40470d0ca5241b795c2b75a932d46900761

#723 is being combined with #915
