### ISSUE TITLE
Update REST syntax for pagination

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#934]
To be more consistent with other APIs, change `start` and `stop` to `limit` and `offset`. Also remove `after` parameter as it should no longer be needed with Elasticsearch removed.

**Comment by bctcvai** [comment]
I propose we leave `after` but rename `start`/`stop` to the proposed values. `after` can come in handy still for pagination and has minimal impact on query complexity in SQL. E.g., A lot of the UI code depends on it now, and changing it to not work with after seems like unnecessary churn.

**Comment by bctcvai** [comment]
Just looking into this further, I might say the rest may not really be worth the trouble. Beyond just the named API parameters, they are forwarded into code in a lot of places as start/stop local variables so it'd be a pretty large refactor changing verbiage w/o any real gain. (start vs. offset isn't really a big deal to me)

That being said, I didn't realize Medias used `after_id`, vs. `after` -- this seems suboptimal, so I suggest we retool this issue to focus solely on rectifying that vs. renaming the parameters.

**Comment by bctcvai** [comment]
A PR on the above resolution is here: https://github.com/cvisionai/tator/pull/978
