### ISSUE TITLE
Makefile should have a global test target

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#94]
Global test target can:

- invoke pytator test
- call other sanity checks (like verify each that gets built does something useful, like import pytator)

**Comment by jrtcppv** [comment]
Is this supposed to be inclusive of the REST API tests invoked via `make test`?

**Comment by bctcvai** [comment]
Good point. Maybe a couple different targets. The pytator level tests flex
the job server so we get good coverage, but don't have a lot of negative
tests in there.

Maybe we can make it based on whether debug is true in the yaml instead.

**Comment by bctcvai** [comment]
we have a `make pytest` now
