### ISSUE TITLE
Review GetClip and GetFrame endpoint outputs for av1 videos

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#952]
It is unclear if the outputs from the GetClip and GetFrame endpoints are correct for av1 encoded videos. In one use-case, the number of frames returned from the GetClip video is larger than expected. A unit test to verify the outputs from these endpoints with equivalent av1 and libx264 videos should be incorporated into the automated test framework

**Comment by bctcvai** [comment]
An option to re-encode av1 encoded videos was added in [#1042](https://github.com/cvisionai/tator/pull/1042).
