### ISSUE TITLE
Add localizations and states to the project detail view's filter UI

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#956]
Currently the project detail view's filter interface only has the Media option. It would be helpful for annotators to also have the option to filter using localization and/or state conditions. This would utilize the current `annotation_search` parameter of the `/rest/Medias`  endpoint. There will be an equivalent parameter in the schema rework expected in the v1 release.

**Comment by bctcvai** [comment]
@marktaipan-cvisionai , this will be in the v1.0.0 branch

**Comment by bctcvai** [comment]
This is closed on `dev/v1.0.0`
