### ISSUE TITLE
Self-hosted dependencies

### ISSUE THREAD

**Issue by henxing** [cvisionai/tator#966]
Downloading certain dependencies is throttled in CI and depending on static download URLs isn't the most robust. This is an attempt at an exhaustive list of static URLs we depend on, most or all of which could be self-hosted in a public aws bucket:

## From the install script 
* bento4: http://zebulon.bok.net/Bento4/binaries/Bento4-SDK-1-6-0-632.x86_64-unknown-linux.zip
* kubectl: https://dl.k8s.io/release/v1.22.9/bin/linux/amd64/kubectl
* argo client: https://github.com/argoproj/argo-workflows/releases/download/v3.3.1/argo-linux-amd64.gz
* argo manifest: https://github.com/argoproj/argo-workflows/releases/download/v3.3.1/install.yaml
* node setup script: https://deb.nodesource.com/setup_16.x
* mc: https://dl.min.io/client/mc/release/linux-amd64/mc

## From CI
* docker: https://get.docker.com
* chrome: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
* pip: https://bootstrap.pypa.io/get-pip.py

## From tator-py
* test video: http://www.ballastmedia.com/wp-content/uploads/AudioVideoSyncTest_BallastMedia.mp4
* test image: https://www.gstatic.com/webp/gallery/1.jpg
* test image set: http://vis-www.cs.umass.edu/lfw/lfw.tgz

**Comment by bctcvai** [comment]
This is at least partially completed -- the ballastmedia one I know has been moved over.
