### ISSUE TITLE
Use helm chart for kubernetes dashboard

### ISSUE THREAD

**Issue by henxing** [cvisionai/tator#974]
[Previously](https://github.com/cvisionai/tator/blob/a9396b8b9c0360097825997f7474ed32fb0b7f6a/Makefile#L129), there was no helm chart for the version of the kubernetes dashboard we were using. Now, there are [many options](https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard). Replace the current `kubectl apply ...` with the correct helm chart.

**Comment by jrtcppv** [comment]
OBEd by #961.
