### ISSUE TITLE
Add support for POSTing multiple media objects

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#994]
Primarily to support image uploads, modify the `Media` `POST` method to accept a list of media specs. This may require some async processing to handle image copies/conversion. This functionality will replace the functionality of archive-based uploads, therefore archive uploads should be deprecated as part of this issue.

**Comment by henxing** [comment]
* Make all *_list methods' bodies take `oneOf` an array of specs or just a single spec
* Update the version of the python openapi code generator we're using
* Check to see if the generator makes the same argument name as before
* If so, profit!
* If not, it will be `body` and any `*_spec` keyword arguments will need to be renamed to `body`

**Comment by henxing** [comment]
Generator upgrade will require a ton of rework and at first glance it does not fix the argument name, so leave the upgrade for later.

**Comment by bctcvai** [comment]
Removed API breaking tag, it isn't breaking the REST API; but does change tator-py function signatures. Not trying to be pedantic, but a different tag may be more appropriate there.

**Comment by henxing** [comment]
Closed by #1078.
