### ISSUE TITLE
Allow for batch name changes in dashboard view

### ISSUE THREAD

**Issue by Giovanna43** [cvisionai/tator#998]
It would be very useful to have the ability to make bulk batch name changes in dashboard view where you see the project summary. This might be easier than going onto correction mode.

**Comment by jrtcppv** [comment]
@Giovanna43 just want to clarify, is the proposal to basically merge the localization analytics view and localization corrections view capabilities into one view? I believe this is what was proposed in #751 and it was addressed by putting in a toggle button. Given this is a repeat request I am inclined to move toward a true single view as was previously laid out. @ermbutler any thoughts on this?

**Comment by ermbutler** [comment]
Got more clarification on this - it is in regard to a specific project dashboard.

**Comment by ermbutler** [comment]
Work was completed for a project dashboard to bulk edit Animal names in the applets repo.
